package com.nicholas.rutherford.track.your.shot.navigation

object NavigationDestinations {
    const val AUTHENTICATION_SCREEN = "authenticationScreen"
    const val AUTHENTICATION_SCREEN_WITH_PARAMS = "authenticationScreen/{username}/{email}"
    const val CREATE_ACCOUNT_SCREEN = "createAccountScreen"
    const val CREATE_EDIT_PLAYER_SCREEN = "createEditPlayerScreen"
    const val CREATE_EDIT_PLAYER_SCREEN_WITH_PARAMS = "createEditPlayerScreen/{firstName}/{lastName}"
    const val FORGOT_PASSWORD_SCREEN = "forgotPasswordScreen"
    const val LOG_SHOT_WITH_PARAMS = "logShotScreen/{isExistingPlayer}/{playerId}/{shotType}/{shotId}/{viewCurrentExistingShot}/{viewCurrentPendingShot}"
    const val LOG_SHOT_SCREEN = "logShotScreen"
    const val ONBOARDING_EDUCATION_SCREEN = "onboardingEducationScreen"
    const val PERMISSION_EDUCATION_SCREEN = "permissionEducationScreen"
    const val ENABLED_PERMISSIONS_SCREEN = "enabledPermissionsScreen"
    const val TERMS_CONDITIONS_SCREEN = "termsConditionsScreen"
    const val TERMS_CONDITIONS_WITH_PARAMS = "termsConditionsScreen/{isAcknowledgeConditions}"
    const val SELECT_SHOT_SCREEN = "selectShotScreen"
    const val SELECT_SHOT_SCREEN_WITH_PARAMS = "selectShotScreen/{isExistingPlayer}/{playerId}"
    const val PLAYERS_LIST_SCREEN = "playersListScreen"
    const val LOGIN_SCREEN = "loginScreen"
    const val SPLASH_SCREEN = "splashScreen"
    const val COMPARE_PLAYERS_SCREEN = "comparePlayersScreen"
    const val SETTINGS_SCREEN = "settingsScreen"
    const val STATS_SCREEN = "statsScreen"
    const val VOICE_COMMANDS_SCREEN = "voiceCommandsScreen"
}
