package com.nicholas.rutherford.track.your.shot.navigation

object NavigationDestinations {
    const val ACCOUNT_INFO_SCREEN = "accountInfoScreen"
    const val ACCOUNT_INFO_SCREEN_PARAMS = "accountInfoScreen/{username}/{email}"
    const val AUTHENTICATION_SCREEN = "authenticationScreen"
    const val AUTHENTICATION_SCREEN_WITH_PARAMS = "authenticationScreen?username={username}&email={email}"
    const val CREATE_ACCOUNT_SCREEN = "createAccountScreen"
    const val CREATE_EDIT_DECLARED_SHOTS_SCREEN = "createEditDeclaredShotsScreen"
    const val CREATE_EDIT_PLAYER_SCREEN = "createEditPlayerScreen"
    const val CREATE_EDIT_PLAYER_SCREEN_WITH_PARAMS = "createEditPlayerScreen?firstName={firstName}&lastName={lastName}"
    const val DECLARED_SHOTS_LIST_SCREEN = "declaredShotsListScreen"
    const val FORGOT_PASSWORD_SCREEN = "forgotPasswordScreen"
    const val LOG_SHOT_WITH_PARAMS = "logShotScreen?isExistingPlayer={isExistingPlayer}&playerId={playerId}&shotType={shotType}&shotId={shotId}&viewCurrentExistingShot={viewCurrentExistingShot}&viewCurrentPendingShot={viewCurrentPendingShot}&fromShotList={fromShotList}"
    const val ONBOARDING_EDUCATION_SCREEN = "onboardingEducationScreen"

    const val ONBOARDING_EDUCATION_SCREEN_WITH_PARAMS = "onboardingEducationScreen?isFirstTimeLaunched={isFirstTimeLaunched}"
    const val PERMISSION_EDUCATION_SCREEN = "permissionEducationScreen"
    const val ENABLED_PERMISSIONS_SCREEN = "enabledPermissionsScreen"
    const val TERMS_CONDITIONS_SCREEN = "termsConditionsScreen"
    const val TERMS_CONDITIONS_WITH_PARAMS = "termsConditionsScreen?shouldAcceptTerms={shouldAcceptTerms}"
    const val SELECT_SHOT_SCREEN = "selectShotScreen"
    const val SELECT_SHOT_SCREEN_WITH_PARAMS = "selectShotScreen?isExistingPlayer={isExistingPlayer}&playerId={playerId}"
    const val PLAYERS_LIST_SCREEN = "playersListScreen"
    const val REPORTS_LIST_SCREEN = "reportsListScreen"
    const val CREATE_REPORT_SCREEN = "createReportScreen"
    const val LOGIN_SCREEN = "loginScreen"
    const val SPLASH_SCREEN = "splashScreen"
    const val COMPARE_PLAYERS_SCREEN = "comparePlayersScreen"
    const val SHOTS_LIST_SCREEN = "shotsListScreen"
    const val SHOTS_LIST_SCREEN_WITH_PARAMS = "shotsListScreen?shouldShowAllPlayersShots={shouldShowAllPlayersShots}"
    const val ACCOUNT_INFO_SCREEN_WITH_PARAMS = "accountInfoScreen?username={username}&email={email}"
    const val SETTINGS_SCREEN = "settingsScreen"
    const val STATS_SCREEN = "statsScreen"
    const val VOICE_COMMANDS_SCREEN = "voiceCommandsScreen"
}
