name: Kover Coverage
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Unit tests coverage for project in debug variant
        run: ./gradlew koverHtmlReportdebug
