name: Lint Checks
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Lint Checks
        run: ,/gradlew ktlintCheck