name: Maestro UI Tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Build debug APK
        run: ./gradlew assembleDebug
      
      - name: Setup Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
      
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: |
            # Install the debug APK
            adb install app/build/outputs/apk/debug/app-debug.apk
            
            # Verify app is installed
            adb shell pm list packages | grep -q "com.nicholas.rutherford.track.your.shot.debug"
            
            # Start the app
            adb shell am start -n com.nicholas.rutherford.track.your.shot.debug/com.nicholas.rutherford.track.your.shot.MainActivity
            
            # Wait for app to load
            sleep 5
            
            # Run Maestro tests (matching local script path)
            maestro test maestro-tests/login
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: maestro-test-results
          path: maestro-tests/results/
